// What the service worker has to hold for the game to run with no network:
// the page, every module under src/, the manifest and the icons. The cache
// version is a hash of all of it, so no shipped file can change without the
// worker changing too - and a changed worker is what browsers treat as an
// update.

import { readFileSync, readdirSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, relative, sep } from 'node:path';

/** Every file the deployed site needs, relative to the site root, sorted. */
export function shippedFiles(root) {
  const out = ['index.html', 'manifest.json'];
  const walk = (dir, keep) => {
    for (const name of readdirSync(dir).sort()) {
      const full = join(dir, name);
      if (statSync(full).isDirectory()) walk(full, keep);
      else if (keep(name)) out.push(relative(root, full).split(sep).join('/'));
    }
  };
  walk(join(root, 'src'), (n) => n.endsWith('.js'));
  walk(join(root, 'icons'), (n) => n.endsWith('.png'));
  return out.sort();
}

/** A short content hash over every shipped file, names included. */
export function cacheVersion(root, files = shippedFiles(root)) {
  const h = createHash('sha256');
  for (const f of files) {
    h.update(f);
    h.update('\0');
    h.update(readFileSync(join(root, f)));
    h.update('\0');
  }
  return h.digest('hex').slice(0, 12);
}

const BLOCK = /\/\/ <precache>[\s\S]*?\/\/ <\/precache>/;

/** The generated block that sits between the markers in sw.js. */
export function precacheBlock(root) {
  const files = shippedFiles(root);
  const lines = ['./', ...files].map((f) => `  './${f === './' ? '' : f}',`);
  return [
    '// <precache> generated by tools/sw-manifest.js - do not edit by hand',
    `const VERSION = '${cacheVersion(root, files)}';`,
    'const PRECACHE = [',
    ...lines,
    '];',
    '// </precache>',
  ].join('\n');
}

/** sw.js with its block brought up to date. */
export function stampWorker(source, root) {
  if (!BLOCK.test(source)) throw new Error('sw.js has no // <precache> ... // </precache> block');
  return source.replace(BLOCK, precacheBlock(root));
}
