// Brackenfall's service worker. It keeps a copy of every file the game needs
// so the whole thing plays with no network after the first visit.
//
// Cache-first: a precached file is always answered from the cache, and the
// network is only asked for things that were never precached. What keeps that
// from going stale is the version: it is a hash of every shipped file, so any
// deploy that changes a file ships a different sw.js, the browser installs it
// alongside the running one, and the page offers a reload. Old caches are
// deleted once the new worker takes over.

// <precache> generated by tools/sw-manifest.js - do not edit by hand
const VERSION = '07353749c2a8';
const PRECACHE = [
  './',
  './icons/apple-touch-icon.png',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon-maskable-192.png',
  './icons/icon-maskable-512.png',
  './index.html',
  './manifest.json',
  './src/data/font.js',
  './src/data/music.js',
  './src/data/palette.js',
  './src/data/rooms/dungeon1.js',
  './src/data/rooms/dungeon2.js',
  './src/data/rooms/overworld.js',
  './src/data/sprites.js',
  './src/data/tiles.js',
  './src/engine/audio.js',
  './src/engine/input.js',
  './src/engine/loop.js',
  './src/engine/render.js',
  './src/engine/storage.js',
  './src/game/bosses.js',
  './src/game/combat.js',
  './src/game/constants.js',
  './src/game/dialogue.js',
  './src/game/enemies.js',
  './src/game/game.js',
  './src/game/player.js',
  './src/game/props.js',
  './src/game/rng.js',
  './src/game/save.js',
  './src/game/tilemap.js',
  './src/game/world.js',
  './src/main.js',
  './src/pwa.js',
];
// </precache>

const PREFIX = 'brackenfall-';
const CACHE = `${PREFIX}${VERSION}`;
const INDEX = new URL('./index.html', self.registration.scope).href;

self.addEventListener('install', (event) => {
  // `reload` goes past the HTTP cache, so a fresh worker never precaches a
  // file the browser had kept from the previous deploy.
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(
      PRECACHE.map((url) => new Request(url, { cache: 'reload' })),
    )),
  );
  // No skipWaiting here. An update waits until the player says to reload, so
  // a running game is never swapped out from under them. (The very first
  // install has nothing to wait for and activates at once.)
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith(PREFIX) && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin || !url.href.startsWith(self.registration.scope)) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    // Any navigation inside the app is the one page the game has.
    const hit = req.mode === 'navigate'
      ? await cache.match(INDEX)
      : await cache.match(req, { ignoreSearch: true });
    return hit ?? fetch(req);
  })());
});
